FROM dustynv/ros:noetic-pytorch-l4t-r35.2.1
############################## SYSTEM PARAMETERS ##############################
# * Arguments
ARG ENTRYPOINT_FILE=entrypint.sh

# * Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
# ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# * Replace apt urls
# ? Change to tku
RUN sed -i 's@archive.ubuntu.com@ftp.tku.edu.tw@g' /etc/apt/sources.list
# ? Change to Taiwan
# RUN sed -i 's@archive.ubuntu.com@tw.archive.ubuntu.com@g' /etc/apt/sources.list

# * Time zone
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/"${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone

# * Copy entrypoint
# ? Requires docker version >= 17.09
COPY --chmod=0775 ./${ENTRYPOINT_FILE} /entrypoint.sh
COPY --chmod=0775 config config
# ? docker version < 17.09
# COPY ./${ENTRYPOINT_FILE} /entrypoint.sh
# RUN sudo chmod 0775 /entrypoint.sh
# COPY config config
# RUN sudo chown -R "${USER}":"${GROUP}" config \
    # && sudo chmod -R 0775 config

############################### INSTALL #######################################
# * Install packages
RUN dpkg --add-architecture armhf && \
    apt update && \
    apt install -y --no-install-recommends \
        sudo \
        git \
        htop \
        wget \
        curl \
        psmisc \
        lsb-release \
        build-essential \
        # * Shell
        tmux \
        terminator \
        # * base tools
        vim \
        pkg-config \
        python3-pip \
        python3-dev \
        python3-setuptools \
        # * usb_cam
        libfreetype6-dev \
        libpng-dev \
        libv4l-dev \
        v4l-utils \
        # * Work tools
        ros-noetic-rosserial-python \
        ros-noetic-turtlebot3-msgs \
        ros-noetic-gmapping \
        ros-noetic-hls-lfcd-lds-driver \
        python3-rosdep \
        python3-rosinstall \
        python3-rosinstall-generator \
        python3-wstool \
        python3-catkin-tools \
        ros-noetic-urdf \
        ros-noetic-xacro \
        ros-noetic-interactive-markers \
        libavcodec-dev \
        libswscale-dev \
        ros-noetic-camera-info-manager \
        libc6:armhf \
    && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# * Install pytorch-YOLOv4
RUN git clone https://github.com/Tianxiaomo/pytorch-YOLOv4 /root/pytorch-YOLOv4 && \
    ./config/pip/pip_setup.sh

ENV ROS_MASTER_URL=http://192.168.50.206:11311
ENV ROS_HOSTNAME=192.168.50.206
ENV ROS_IP=192.168.50.206
ENV TURTLEBOT3_MODEL=burger
ENV LDS_MODEL=LDS-01
ENV OPENCR_PORT=/dev/opencr
ENV OPENCR_MODEL=burger_noetic

############################## USER CONFIG ####################################
# * Setup user configuration
RUN ./config/shell/bash_setup_for_root.sh && \
    ./config/shell/terminator/terminator_setup_for_root.sh && \
    ./config/shell/tmux/tmux_setup_for_root.sh && \
    sudo rm -rf /config

# * Switch workspace to /home/"${USER}"/work
RUN sudo mkdir -p /root/work

WORKDIR /root/work

# * Make SSH available
# EXPOSE 22

# ENTRYPOINT [ "/entrypoint.sh", "terminator" ]
ENTRYPOINT [ "/entrypoint.sh", "tmux" ]
# ENTRYPOINT [ "/entrypoint.sh", "bash" ]
# ENTRYPOINT [ "/entrypoint.sh" ]
